
import json


def read_json(file_name):
    with open(file_name, 'r') as file:
        data = json.load(file)
    return data


def remove_coma_from_dic(python_file):
    if python_file[len(python_file)-2] == ',':
        python_file = python_file[:(len(python_file)-2)]
        python_file += '\n'
    return python_file


def get_mapping_intelligence_data(file_brand, file_model):
    brand_data = read_json(file_brand)
    model_data = read_json(file_model)
    python_file = """
# autogenerated code for BRAND mapping replace
BRAND_MAP = {
"""
    for brand in brand_data:
        brand_name = brand['brand']
        python_file += f"    'REPLACE-{brand_name}': '{brand_name}',\n"

    python_file = remove_coma_from_dic(python_file)
    python_file += "}\n"

    python_file += '\n# autogenerated code for MODEL mapping replace\n'
    python_file += 'MODEL_MAP = {\n'
    for brand_name, brand_value in model_data.items():
        model_list = brand_value['model_list']
        for pos, model in enumerate(model_list):
            python_file += f"    '{brand_name}-REPLACE({pos})': '{model}',\n"

    python_file = remove_coma_from_dic(python_file)
    python_file += "}\n"

    return python_file


def run_intelligence(file_brand, file_model, python_output_file):
    data_python = get_mapping_intelligence_data(file_brand, file_model)
    with open(python_output_file, 'w') as file:
        file.write(data_python)
